### ISSUE TITLE
Events do not show up in Daily View

### ISSUE THREAD

**Issue by as96** [as96/3354-DeathBySegmentationFault#11]

**Comment by gcmvy3** [comment]
I have looked at this issue but not fixed it yet. CreateEventActivity successfully creates the event and adds it to eventlistmanager. However, calling eventListManager.getEventsBetween does not return any events. That means either:

-The parameters being passed into getEventsBetween() are wrong
-The event is being stored incorrectly in eventlistmanager
-The getEventsBetween() method does not work

**Comment by gcmvy3** [comment]
This issue has been fixed by Trent
