### ISSUE TITLE
Move add event button to monthly view?

### ISSUE THREAD

**Issue by as96** [as96/3354-DeathBySegmentationFault#15]
Some thing I noticed: It seems kind of odd to me that you can click to go to a day that's earlier than the current one, but can click the add event button on a day that's already passed and it'll make a new event starting for the current day. It's more of a design issue than an actual bug, but if you give it a try then you might understand what I'm getting at. Feedback would be appreciated.

**Comment by gcmvy3** [comment]
Add event button has been added, default event date is fixed
